#lang racket/base
(provide (all-defined-out))
(define (quote-symbol q)
  (hash-ref q `symbol #f))
(define (quote-last-price q)
  (hash-ref q `last #f))
(define (quote-venue q)
  (hash-ref q `venue #f))
(define (quote-bid q)
  (hash-ref q `bid #f))
(define (quote-bid-size q)
  (hash-ref q `bidSize #f))
(define (quote-bid-depth q)
  (hash-ref q `bidDepth #f))
(define (quote-ask q)
  (hash-ref q `ask #f))
(define (quote-ask-size q)
  (hash-ref q `askSize #f))
(define (quote-ask-depth q)
  (hash-ref q `askDepth #f))
(define (quote-last-size q)
  (hash-ref q `lastSize #f))
(define (quote-last-time q)
  (hash-ref q `lastTrade #f))
(define (quote-time q)
  (hash-ref q `quoteTime #f))
(module+ test
  (require rackunit)
  (define q '#hasheq((symbol . "OJUK")
         (ok . #t)
         (last . 4393)
         (venue . "ESYHEX")
         (bid . 4061)
         (bidSize . 460)
         (askSize . 28)
         (bidDepth . 1380)
         (askDepth . 84)
         (lastSize . 40)
         (lastTrade . "2015-11-29T06:38:18.768165487Z")
         (ask . 4275)
         (quoteTime . "2015-11-29T06:38:18.790384463Z")))
  (check-equal? (quote-last-price q) 4393)
  (check-equal? (quote-venue q) "ESYHEX")
  (check-equal? (quote-bid q) 4061)
  (check-equal? (quote-bid-size q) 460)
  (check-equal? (quote-bid-depth q) 1380)
  (check-equal? (quote-ask q) 4275)
  (check-equal? (quote-ask-size q) 28)
  (check-equal? (quote-ask-depth q) 84)
  (check-equal? (quote-last-size q) 40))